server {
    listen 80;
    server_name back.toggolac.com www.back.toggolac.com;

    root /var/www/html/public;
    index index.php index.html index.htm;

    location / {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization, X-Requested-with' always;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors on;
    }

    location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
        expires max;
        log_not_found off;
    }

    # Permitir que Nginx sirva archivos de la carpeta storage
    location /storage/ {
        alias /var/www/html/storage/app/public/;
        access_log off;
        expires 30d;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}

